// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:

        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgROBqsqig3OrhcR6y2Ai21rARYO25pA',
    appId: '1:617819190113:web:c471e719ba1327f8228b20',
    messagingSenderId: '617819190113',
    projectId: 'project-20179432-3457-4d7f-9c5',
    authDomain: 'project-20179432-3457-4d7f-9c5.firebaseapp.com',
    storageBucket: 'project-20179432-3457-4d7f-9c5.firebasestorage.app',
    measurementId: 'G-HHRXMBQTF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59lNHnFI_gkNzrElPGtjzw6wGEvsvYPQ',
    appId: '1:617819190113:android:83740ea2228b3e50228b20',
    messagingSenderId: '617819190113',
    projectId: 'project-20179432-3457-4d7f-9c5',
    storageBucket: 'project-20179432-3457-4d7f-9c5.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59lNHnFI_gkNzrElPGtjzw6wGEvsvYPQ',
    appId: '1:617819190113:ios:0d2ef5d085e1dbd8228b20',
    messagingSenderId: '617819190113',
    projectId: 'project-20179432-3457-4d7f-9c5',
    storageBucket: 'project-20179432-3457-4d7f-9c5.firebasestorage.app',
    iosBundleId: 'com.autodevops.frontendFlutter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm6N_CgKq-4X_L69u8K6e2r8Yt1c3X6X9X',
    appId: '1:617819190113:ios:5a1d3b8a9d1e3f5c6d7e8a1',
    messagingSenderId: '617819190113',
    projectId: 'project-20179432-3457-4d7f-9c5',
    storageBucket: 'project-20179432-3457-4d7f-9c5.firebasestorage.app',
    iosBundleId: 'com.autodevops.frontendFlutter',
  );
}
